export const LEETCODE_TAGS: string[] = [
  "Array",
  "String",
  "Hash Table",
  "Linked List",
  "Stack",
  "Queue",
  "Heap",
  "Tree",
  "Binary Tree",
  "Binary Search Tree",
  "Graph",
  "Trie",
  "Backtracking",
  "Recursion",
  "Dynamic Programming",
  "Greedy",
  "Sliding Window",
  "Two Pointers",
  "Binary Search",
  "DFS",
  "BFS",
  "Bit Manipulation",
  "Matrix"
];
